name: Deploy To IRIS
description: Send created, modigfied and deleted files to IRIS. Compile and return result of compilation.
inputs:
  host:
    description: Host name or IP addres of WebSrever that communicate with IRIS server.
    required: true
  port:
    description: port number of WebSrever that communicate with IRIS.
    required: true
    default: "52773"
  namespace_iris:
    description: Name of IRIS namespace to deploy.
    required: true
  https:
    description: Flag indicting uses of HTTPS by the WebServer. 1-true, 0-false
    required: true
    default: "0"
  base_api_url:
    description: The base URL to IRIS Source Code File REST API
    required: true
    default: "/api/atelier/"
  version_api:
    description: The version of IRIS Source Code File REST API.
    required: true
    default: "v2"
  compilation_flags:
    description: Flags used by the IRIS compiler. See
    required: true
    default: "cukb"
  source_path:
    description: The source root path. Need to be extracted from source file name.
    required: true
    default: "src/"
  iris_usr:
    description: Iris user name
    required: true
  iris_pwd:
    description: Iris user pwd
    required: true
  changed_files:
    description: Comma delimited string with a list of changed files to deploy.
    required: true
  deleted_files:
    description: Comma delimited string with a list of deleted files to delete from server.
    required: true
runs:
  using: 'docker'
  image: "Dockerfile"