# Workflow etemplate to Create, Upate, Delete and Compile source documents on IRIS
name: Deploy to IRIS
# Trigger execute action
on:
  push:
    # All push to these branchs trigger the action Deploy to IRIS 
    branches:
      - main
   # All puspull_requesth to these branchs trigger the action Deploy to IRIS
  pull_request:
    branches:
      - main
  # Allow manually worflow execution
  workflow_dispatch:

jobs:
  deploy-to-iris:
    runs-on: ubuntu-latest
    steps:
      - name: Depoly to IRIS
        uses: ./
        with:
          # Use github secrets 
          host: '<IP or Host Name>'
          port: '<Port Number>'
          namespace_iris: '<CODENAMESPACE>'
          # 0 - HTTP, 1 - HTTPS 
          https: '0'
          base_api_url: '/api/atelier'
          version_api: 'v2'
          # Change if you don't want default flags compilation
          compilation_flags: 'cukb'
          # Used to extract from document name before sen to IRIS, avoiding Document Not found error.
          source_path: 'src/'
          # Use github secrets
          iris_usr: 'usr'
          iris_pwd: 'pwd'
